// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdQAOJ1oTLDrJ-bj7MiL4zSGL_rGI2O98',
    appId: '1:998540516249:web:00927f6ea9ce25b2c01108',
    messagingSenderId: '998540516249',
    projectId: 'shop-firebase-f0336',
    authDomain: 'shop-firebase-f0336.firebaseapp.com',
    databaseURL: 'https://shop-firebase-f0336-default-rtdb.firebaseio.com',
    storageBucket: 'shop-firebase-f0336.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLnI4vru9U5Z8RW0pD6hCoMtQWo4p11ls',
    appId: '1:998540516249:android:c2feed4cab6b43bec01108',
    messagingSenderId: '998540516249',
    projectId: 'shop-firebase-f0336',
    databaseURL: 'https://shop-firebase-f0336-default-rtdb.firebaseio.com',
    storageBucket: 'shop-firebase-f0336.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRfcyLZkfhqqKqVAO72Qq6g9D-oe2neiI',
    appId: '1:998540516249:ios:43e29a1be2d68eabc01108',
    messagingSenderId: '998540516249',
    projectId: 'shop-firebase-f0336',
    databaseURL: 'https://shop-firebase-f0336-default-rtdb.firebaseio.com',
    storageBucket: 'shop-firebase-f0336.appspot.com',
    iosClientId: '998540516249-mn4h0kjojqho8e57ka25uerdlie74k14.apps.googleusercontent.com',
    iosBundleId: 'com.cuongtran.shopFirebase',
  );
}
